### ISSUE TITLE
Wallpaper Prompt not loading

### ISSUE THREAD

**Issue by torrancew** [lynnard/VIMonad#4]
I can't seem to load the wallpaper prompt with the `M-z` keystroke listed in the docs. I have confirmed that feh, wallhaven and rss-image-download are all available, am I missing some other application, possibly?

**Comment by lingnand** [comment]
You need to confirm these directories exist:

```
mkdir -p $HOME/Pictures/wallpapers/{'#favorites','#rss','#standard'}
```

The `#favorites` stores images you 'liked' inside the Wallpaper prompt, `#rss` stores directories of images obtained from `rss-image-download`, `#standard` stores images obtained from `wallhaven` via default settings (this is also the default channel).

Some quick guides:
- each directory/subdirectory inside `$HOME/Pictures/wallpapers` is called a channel
- the wallpaper prompt is designed to choose pictures inside a channel
- you can change channel via `setch <ch>` or `wallhaven <ch>` or `flickr <ch>`
  - `setch <ch>` sets the channel to `<ch>`, autocompletion is available
    - if `<ch>` is not a directory inside `wallpapers`, it automatically triggers `wallhaven <ch>` to download images to that channel. e.g., `setch TV/Archer`, this will search and download images for `Archer` into `TV/Archer`
  - `wallhaven <ch>` always downloads the images into `<ch>` regardless of whether that `<ch>` exists; this is what you want initially because I assume you don't have any wallpapers from the start
  - `flickr <ch>` downloads images into `<ch>` using flickr, note that pictures searched using flickr might not be well-suited for wallpaper
- Wallpaper prompt always chooses a picture randomly
  - `next` chooses the next random picture inside the current channel
  - `rate` copies the current image into `#favorites`
  - `ban` bans the image - puts it to `$HOME/Pictures/others` so that the prompt will never stumble onto the image again
  - `trash` deletes the image - puts it to `$HOME/.Trash`
- some keybindings are available inside the prompt (so you can `<M-z><M-n>` to switch to the next random wallpaper
  - `M-n`: `next`
  - `M-s`: `setch` 
  - `M-u`: `ban`
  - `M-a`: `rate`
  - `M-t`: `trash`
  - `M-f`: `flickr`

Sorry this should really be in the doc from the start. Remember to pop back to confirm if it works or not on your system.

**Comment by torrancew** [comment]
@lynnard Thanks! Adding the subdirectories allowed the prompt to appear, and I grasp the concept of what's going on, however, there definitely appears to a quirk or two. Currently, preview/setting wallpaper isn't functioning from the wallpaper prompt. "next" seems to have no effect at all, though I can issue setch commands. Downloading is a bit quirky as well, but some of that may be my unfamiliarity with wallhaven.

Are there any requirements or expectations about what wallpaper files are named inside of channel directories? I would like to use some existing wallpaper directories with this tool, if possible.

**Comment by torrancew** [comment]
I also wanted to confirm what the requirements were for the transparent functionality. I have 2 machines I'm testing vimonad on, and one is a clean arch install, so it currently has no compositing tool installed.

**Comment by lingnand** [comment]
Have you put down `wallpaper-change` somewhere? Make sure that `wallpaper-change <directory>` works before trying the Wallpaper Prompt.

If you take a look at `wallpaper-change` you'll realise there really isn't any magic there - any image ending with `.png` or `.jpg` works fine. If you need to support more image formats just add the extensions into the script.

For the transparency to work you need to install `compton`.

**Comment by lingnand** [comment]
Oh, forgot to mention: `wallpaper-change` requires `imagemagick` to work, so that might be what's missing on your machine. The quirks you mentioned should go away when all the required programs are found as well.

**Comment by torrancew** [comment]
Ok, thanks for the heads up! I have `wallpaper-change` functioning well, but am still having some problems with the prompt.

**Comment by lingnand** [comment]
1. are you able to call `wallpaper-change` from a normal shell (it's inside $PATH)?
2. do windows fade when Wallpaper Prompt is active?

**Comment by torrancew** [comment]
1) yes
2) no, though I only just now installed compton

**Comment by torrancew** [comment]
I take that back! My $PATH for bash is correct, but X is more restricted! Will update after correcting that.

**Comment by lingnand** [comment]
Try putting `compton -cGb` inside your `.xinit`, restarting your computer and see what happens.

**Comment by torrancew** [comment]
With compton running and the X $PATH corrected, things are working now. Thanks!
